### ISSUE TITLE
CliDownloader#getLatestVersion() does not close streams

### ISSUE THREAD

**Issue by bmuschko** [snyk/gradle-plugin#2]
[This method](https://github.com/snyk/gradle-plugin/blob/master/src/main/java/io/snyk/gradle/plugin/CliDownloader.java#L32-L43) creates streams but doesn't close them in a `finally` block. Therefore, those stream stay around for longer than needed.

The same behavior can be observed in the class `Runner`.

**Comment by bmvermeer** [comment]
Technically yes, however in practice the lifetime of the complete runtime is short.
I consider this a minor issue

**Comment by bmuschko** [comment]
Not if you run the Gradle build with the daemon option which is the default. For that reason, you have a potential resource leak.
