### ISSUE TITLE
`snyk-monitor` fails with OOM error

### ISSUE THREAD

**Issue by vnickolov** [snyk/gradle-plugin#22]
Using the Snyk Gradle Plugin version 0.4 after updating to Gradle 7.6 and running `./gradlew snyk-monitor` I am getting an OOM error

> * What went wrong:
>   Execution failed for task ':snykResolvedDepsJson'.
>     Java heap space

the `snyk-cli` version is `v1.1081.0 of snyk-linux`

The same build doesn't raise this error when using Gradle 7.5.1.

Is there a quick way to fix this?

**Comment by nuhkoca** [comment]
@vnickolov Gradle `7.6` is apparently using more memory than `7.5` and this was already reported. As it seems, this should be fixed in the version `7.6.1`. See he related issue here: https://github.com/gradle/gradle/issues/23215

**Comment by vnickolov** [comment]
Thank you @nuhkoca I will give this a try and will close this issue if the problem is resolved.

**Comment by vnickolov** [comment]
I am experiencing this now: https://github.com/gocd/gocd/pull/11334
I guess the issue here can be closed and I can monitor the Gradle repository instead.

**Comment by nuhkoca** [comment]
Ohh that's too bad to hear 😢 @vnickolov

**Comment by vnickolov** [comment]
Thank you 🙇 I am closing this issue here and will carry on checking the Gradle repository issues.
