### ISSUE TITLE
Version 0.4 still contains vulnerability to org.json

### ISSUE THREAD

**Issue by mishabhi** [snyk/gradle-plugin#27]
It is visible from the commit https://github.com/snyk/gradle-plugin/commit/a80054aa0ec29fe9a77c8462905c8d198005aea5 that the org.json dependency is upgraded but it appears the plugin on gradle repository is still 0.4.

Because of above synchronization mismatch, this plugin itself is producing a high level of vulnerability.

![image](https://github.com/snyk/gradle-plugin/assets/16177376/d3415aaf-85a0-48f1-9d48-f0b8572704b1)

Please may I request to publish a new plugin version with the latest changes?

**Comment by josephearl** [comment]
+1, can we get a release of the plugin please?

**Comment by bmvermeer** [comment]
0.5 just released
