### ISSUE TITLE
CliDownloader#downloadLatestVersion() uses internal Gradle classes

### ISSUE THREAD

**Issue by bmuschko** [snyk/gradle-plugin#3]
While convenient, internal Gradle classes should never be used as they can introduce breaking changes with a new Gradle runtime version and therefore may break the consumer of this plugin. Example: https://github.com/snyk/gradle-plugin/blob/master/src/main/java/io/snyk/gradle/plugin/CliDownloader.java#L66

The same behavior can be observed in `SnykBinaryTask`.

**Comment by bmvermeer** [comment]
Great suggestion

**Comment by trevjonez** [comment]
Seems this should be closed. Neither of the classes in the OP are using anything but public gradle API now.
