### ISSUE TITLE
Plugin v0.5.1 reports SNYK-JAVA-ORGJSON-5962464 vulnerability in org.json:json@20230227

### ISSUE THREAD

**Issue by martinrist** [snyk/gradle-plugin#34]
# Overview

Using v.0.5.1 of the plugin on a Gradle project fails, reporting a vulnerability `SNYK-JAVA-ORGJSON-5962464` in `org.json:json@20230227`.

This occurs even if the Gradle project is stripped down to have no explicit dependencies other than the `java` plugin and the this plugin (see attached sample reproduction repository [snyk-gradle-plugin-issue34-repro.zip](https://github.com/snyk/gradle-plugin/files/14221913/snyk-gradle-plugin-issue34-repro.zip)).

# Build Output

```
> ./gradlew snyk-test

...

Tested 1 dependencies for known issues, found 1 issue, 1 vulnerable path.

Issues to fix by upgrading:

  Upgrade org.json:json@20230227 to org.json:json@20231013 to fix
  ✗ Allocation of Resources Without Limits or Throttling [High Severity][https://security.snyk.io/vuln/SNYK-JAVA-ORGJSON-5962464] in org.json:json@20230227
    introduced by org.json:json@20230227
```

The build output is suggesting the project contains one dependency.  Running `./gradlew dependencies` contains the following line in the output:

```
dataFiles - The data artifacts to be processed for this plugin.
\--- org.json:json:20230227
```

If the reference to the Snyk Gradle plugin is removed, then the output of`./gradlew dependencies` no longer includes the reference to this library.

# Build Details

```
> ./gradlew --version

------------------------------------------------------------
Gradle 8.6
------------------------------------------------------------

Build time:   2024-02-02 16:47:16 UTC
Revision:     d55c486870a0dc6f6278f53d21381396d0741c6e

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21 (Amazon.com Inc. 21+35-LTS)
OS:           Mac OS X 14.2.1 aarch64
```

**Comment by martinrist** [comment]
I've dug around in the source code and found that `org.json:json:20230227` (the vulnerable version) is being explicitly added to the dependencies in `io.snyk.gradle.plugin.SnykPlugin#apply`:

```
config.defaultDependencies(dependencies -> dependencies.add(project.getDependencies().create("org.json:json:20230227")));
```

See https://github.com/snyk/gradle-plugin/blob/8ae35167cd26e7a9713a6f944e030c5e5b4faa3b/src/main/java/io/snyk/gradle/plugin/SnykPlugin.java#L21

Updating that line to reference the new version (20231023) and building / running locally seems to address the issue.

[Edit]: It looks like PR #30 (by [CedricFinance](https://github.com/CedricFinance) ) fixes this issue.

**Comment by bmvermeer** [comment]
problem is no longer there since 0.6.1
