### ISSUE TITLE
Severity "critical" not supported

### ISSUE THREAD

**Issue by pablocoberly** [snyk/gradle-plugin#38]
The snyk azure devops task supports a severity threshold of "critical", however this Gradle task seems to only support high, medium, low, or empty.

If you set:

```
    severity = 'critical'
```

You get a Gradle build error:

```
> Severity should either high|medium|low or empty
```

Is it possible to add "critical" as a supported severity threshold or was critical not included for a specific reason?

**Comment by bmvermeer** [comment]
Version 0.7.0 has this now
https://github.com/snyk/gradle-plugin/commit/dac5df0f028bacfa1bfeb6c910b24767ec438057
